Logging: 
  IncludeScopes: false
  Debug:
    LogLevel: 
      Default: Information
  Console:
    LogLevel: 
      Default: Information
eureka:
  client:
    serviceUrl: https://eureka-2187cd14-9f3d-4b87-9360-c4a30f530125.apps.selma.cf-app.com
    validate_certificates: false